services:
  extraction-anr-theses:
    container_name: extraction-anr-theses
    build: .
    mem_limit: ${MEM_LIMIT}
    memswap_limit: ${MEM_LIMIT}
    cpus: ${CPU_LIMIT}
    restart: 'no'
    volumes:
      - "${DATA_PATH}:/starstock"
      - "${OUTPUT_PATH}:/output"
    env_file:
      - .env
    environment:
      - MAX_FILES=${MAX_FILES}
      - OFFSET=${OFFSET}
      - MAX_WORKERS=${MAX_WORKERS}