version: '3.8'

services:
  extraction-anr-theses:
    build: .
    volumes:
      - "${DATA_PATH}:/starstock"
      - "${OUTPUT_PATH}:/output"
    env_file:
      - .env
    environment:
      - MAX_FILES=${MAX_FILES}
      - OFFSET=${OFFSET}
